info:
  date: 20200707
  author: tut
  sign: dev
  version: Ver1.12345-u1
  
spring:
  profiles:
    active: dev
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver